alias k="rlwrap ~/programs/k/k  ~/programs/k/repl.k"
alias krun="~/programs/k/k"
alias csi="rlwrap chicken-csi"
alias R="cd ~/repos"
alias M="cd ~/repos/mlatu"
alias scc="scc --no-size --no-cocomo --no-complexity"
alias ocaml="rlwrap ocaml"
alias N="cd ~/repos/Nial_Development/"
alias i="vim ~/.config/i3/config"
alias s="vim ~/.config/polybar/config.ini"
alias h="vim ~/.config/hypr/hyprland.conf"
set -x DEBUGINFOD_URLS "https://debuginfod.archlinux.org"
alias b="cat /sys/class/power_supply/BAT0/capacity /sys/class/power_supply/AC0/online"
