#!/bin/bash

# setting mouse speed
# centre is (960, 540)
# s 0 (1-s)x 0 s (1-s)y 0 0 1
# xinput set-prop 10 179 0.5 0 480 0 0.5 270 0 0 1
# xinput set-prop 10 179 0.4 0 576 0 0.4 324 0 0 1
xinput set-prop 10 179 0.3 0 672 0 0.3 378 0 0 1

# setting french keyboard
setxkbmap us,ca -option 'grp:win_space_toggle'
