(org-babel-load-file "~/.emacs.d/config.org")
;(setq inhibit-startup-echo-area-message "gator")
;(put 'list-timers 'disabled nil)
;(load-file "~/.emacs.d/config.el")
(put 'dired-find-alternate-file 'disabled nil)
