;;;###theme-autoload
(deftheme quiet
  "Minimal highlighting"
  :background-mode 'dark
  :kind 'color-scheme)

(let* ((class '((class color) (min-colors 89)))
       (default `((,class (:background "#242424" :foreground "#f6f3e8"))))
       (highlight `((,class (:background "#595959")))))
  (custom-theme-set-faces
   'quiet
   `(default ,default)
   `(cursor ((,class (:background "#b7b7b7"))))
   ;; Highlighting faces
   `(fringe ,default)
   `(highlight ,highlight)
   `(region ,highlight)
   `(secondary-selection ,highlight)
   `(isearch ,highlight)
   `(lazy-highlight ,highlight)
   ;; Mode line faces
   `(mode-line ((,class (:foreground "#f6f3e8" :overline t))))
   `(mode-line-inactive ((,class (:foreground "#857b6f"))))
   ;; Escape and prompt faces
   `(minibuffer-prompt ,default)
   `(escape-glyph ,default)
   `(homoglyph ,default)
   ;; Font lock faces
   `(font-lock-builtin-face ,default)
   `(font-lock-comment-face ((,class (:foreground "#799cfc"))))
   `(font-lock-constant-face ,default)
   `(font-lock-function-name-face ,default)
   `(font-lock-keyword-face ,default)
   `(font-lock-string-face ((,class (:foreground "#fcae49"))))
   `(font-lock-type-face ,default)
   `(font-lock-variable-name-face ,default)
   `(font-lock-warning-face ,default)
   `(org-block ,default)
   ;; Help faces
   `(help-key-binding ,default)
   ;; Button and link faces
   `(link ((,class (:foreground "#8ac6f2" :underline t))))
   `(link-visited ((,class (:foreground "#e5786d" :underline t))))
   `(button ((,class (:background "#333333" :foreground "#f6f3e8"))))
   `(header-line ,default)
   ;; Gnus faces
   `(gnus-group-news-1 ,default)
   `(gnus-group-news-1-low ,default)
   `(gnus-group-news-2 ,default)
   `(gnus-group-news-2-low ,default)
   `(gnus-group-news-3 ,default)
   `(gnus-group-news-3-low ,default)
   `(gnus-group-news-4 ,default)
   `(gnus-group-news-4-low ,default)
   `(gnus-group-news-5 ,default)
   `(gnus-group-news-5-low ,default)
   `(gnus-group-news-low ,default)
   `(gnus-group-mail-1 ,default)
   `(gnus-group-mail-1-low ,default)
   `(gnus-group-mail-2 ,default)
   `(gnus-group-mail-2-low ,default)
   `(gnus-group-mail-3 ,default)
   `(gnus-group-mail-3-low ,default)
   `(gnus-group-mail-low ,default)
   `(gnus-header-content ,default)
   `(gnus-header-from ,default)
   `(gnus-header-subject ,default)
   `(gnus-header-name ,default)
   `(gnus-header-newsgroups ,default)
   ;; Message faces
   `(message-header-name ,default)
   `(message-header-cc ,default)
   `(message-header-other ,default)
   `(message-header-subject ,default)
   `(message-header-to ,default)
   `(message-cited-text ,default)
   `(message-separator ,default)
   ;; ANSI colors
   `(ansi-color-black ((,class (:background "#242424" :foreground "#242424"))))
   `(ansi-color-red ((,class (:background "#b85149" :foreground "#b85149"))))
   `(ansi-color-green ((,class (:background "#92a65e" :foreground "#92a65e"))))
   `(ansi-color-yellow ((,class (:background "#ccaa8f" :foreground "#ccaa8f"))))
   `(ansi-color-blue ((,class (:background "#5b98c2" :foreground "#5b98c2"))))
   `(ansi-color-magenta ((,class (:background "#64619a" :foreground "#64619a"))))
   `(ansi-color-cyan ((,class (:background "#3f9f9e" :foreground "#3f9f9e"))))
   `(ansi-color-white ((,class (:background "#f6f3e8" :foreground "#f6f3e8"))))
   `(ansi-color-bright-black ((,class (:background "#444444" :foreground "#444444"))))
   `(ansi-color-bright-red ((,class (:background "#e5786d" :foreground "#e5786d"))))
   `(ansi-color-bright-green ((,class (:background "#95e454" :foreground "#95e454"))))
   `(ansi-color-bright-yellow ((,class (:background "#edc4a3" :foreground "#edc4a3"))))
   `(ansi-color-bright-blue ((,class (:background "#8ac6f2" :foreground "#8ac6f2"))))
   `(ansi-color-bright-magenta ((,class (:background "#a6a1de" :foreground "#a6a1de"))))
   `(ansi-color-bright-cyan ((,class (:background "#70cecc" :foreground "#70cecc"))))
   `(ansi-color-bright-white ((,class (:background "#ffffff" :foreground "#ffffff"))))))

(provide-theme 'quiet)
